[package]
name = "ez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
ariadne = "0.1.5"
clap = "3.2.17"
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
yansi = "0.5"
rand = "0.8.5"
lazy_static = "1.4.0"